version: "3"

services:
  selenium-hub:
    image: selenium/hub:3.141.59-palladium
    ports:
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300
    volumes:
      - /dev/shm:/dev/shm
  chrome:
    image: selenium/node-chrome:3.141.59-palladium
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
  firefox:
    image: selenium/node-firefox:3.141.59-palladium
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    volumes:
      - /dev/shm:/dev/shm      
  jenkins:
    build: ./jenkins
    depends_on:
      - selenium-hub
    restart: always
    environment:
      - JAVA_OPTS=-Djenkins.CLI.disabled=true -Duser.timezone=Australia/Sydney
    ports:
      - 7000:8080
    volumes:
      - jenkins_home:/var/jenkins_home      
    network_mode: host

volumes:
  jenkins_home: